# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 531264a1ff1d174bcc14c7e10ce01ae2d3eceea84c5c9072d5efdde3e6163900cf7abd909ea587dc8789ea5526bcbb4d5f80a974be36a0ce6cd240da46619304

test:
  secret_key_base: 215de469427cf8f032ce1daa037ee5199ccae1ff1841c81e9905902cb48b422012f36265ca8047650b2a62280948b045dc53d54ead0189bdb1e685ca57b4b612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
